export const glossaryCategoryOrder = [
  "거시경제",
  "물가·고용",
  "금리·통화",
  "외환·국제",
  "주식·투자",
  "채권·신용",
  "파생·위험",
  "기업·회계",
  "무역·산업",
  "부동산·가계",
  "원자재·에너지",
  "정책·제도",
  "시장심리·자금",
  "디지털경제"
];

export const glossaryTerms = [
  { term: "국내총생산", english: "GDP, Gross Domestic Product", category: "거시경제", definition: "일정 기간 한 나라 안에서 새로 생산된 최종 재화와 서비스의 시장가치를 합한 값입니다.", related: ["경제성장률", "명목 GDP", "실질 GDP"] },
  { term: "국민총소득", english: "GNI, Gross National Income", category: "거시경제", definition: "국민이 국내외에서 벌어들인 소득을 합한 값으로 국민의 실제 소득 수준을 볼 때 사용합니다.", related: ["GDP", "1인당 GNI", "교역조건"] },
  { term: "경제성장률", english: "Economic Growth Rate", category: "거시경제", definition: "실질 GDP가 이전 기간보다 얼마나 늘거나 줄었는지를 백분율로 나타낸 값입니다.", related: ["실질 GDP", "잠재성장률", "경기순환"] },
  { term: "잠재성장률", english: "Potential Growth Rate", category: "거시경제", definition: "물가를 크게 자극하지 않으면서 노동과 자본을 정상적으로 활용해 달성할 수 있는 성장률입니다.", related: ["GDP 갭", "생산성", "완전고용"] },
  { term: "경기순환", english: "Business Cycle", category: "거시경제", definition: "경제가 회복·확장·둔화·침체를 반복하는 흐름을 뜻합니다.", related: ["경기선행지수", "경기침체", "소프트랜딩"] },
  { term: "경기침체", english: "Recession", category: "거시경제", definition: "생산·소비·투자·고용 등 경제활동이 전반적으로 상당 기간 위축되는 상태입니다.", related: ["실업률", "GDP", "경기순환"] },
  { term: "디플레이션", english: "Deflation", category: "거시경제", definition: "상품과 서비스의 전반적인 가격 수준이 지속적으로 하락하는 현상입니다.", related: ["인플레이션", "부채 디플레이션", "수요부진"] },
  { term: "스태그플레이션", english: "Stagflation", category: "거시경제", definition: "경기 부진과 높은 물가상승이 동시에 나타나는 상태입니다.", related: ["인플레이션", "경기침체", "공급충격"] },
  { term: "소프트랜딩", english: "Soft Landing", category: "거시경제", definition: "중앙은행이 물가를 낮추면서도 심각한 경기침체는 피하는 상황을 뜻합니다.", related: ["금리인상", "디스인플레이션", "고용"] },
  { term: "생산성", english: "Productivity", category: "거시경제", definition: "투입한 노동과 자본에 비해 얼마나 많은 산출을 만들어내는지를 나타냅니다.", related: ["노동생산성", "잠재성장률", "기술혁신"] },

  { term: "소비자물가지수", english: "CPI, Consumer Price Index", category: "물가·고용", definition: "가계가 구입하는 대표 상품과 서비스의 가격 변화를 측정한 지수입니다.", related: ["인플레이션", "근원물가", "생활물가"] },
  { term: "생산자물가지수", english: "PPI, Producer Price Index", category: "물가·고용", definition: "생산자가 국내시장에 공급하는 상품과 서비스의 가격 변화를 측정한 지수입니다.", related: ["CPI", "기업비용", "수입물가"] },
  { term: "근원물가", english: "Core Inflation", category: "물가·고용", definition: "가격 변동이 큰 식품과 에너지 등을 제외해 기조적인 물가 흐름을 보여주는 지표입니다.", related: ["CPI", "서비스물가", "기대인플레이션"] },
  { term: "기대인플레이션", english: "Inflation Expectations", category: "물가·고용", definition: "가계와 기업, 시장이 앞으로 물가가 얼마나 오를 것으로 예상하는지를 뜻합니다.", related: ["임금", "금리", "물가"] },
  { term: "기저효과", english: "Base Effect", category: "물가·고용", definition: "비교 기준인 과거 수치가 너무 높거나 낮아 현재 증가율이 실제보다 크게 달라 보이는 현상입니다.", related: ["전년동월비", "전월비", "증가율"] },
  { term: "고용률", english: "Employment Rate", category: "물가·고용", definition: "생산가능인구 가운데 실제 취업자가 차지하는 비율입니다.", related: ["실업률", "경제활동참가율", "취업자"] },
  { term: "실업률", english: "Unemployment Rate", category: "물가·고용", definition: "경제활동인구 중 일할 의사와 능력이 있지만 일자리를 구하지 못한 사람의 비율입니다.", related: ["고용률", "비경제활동인구", "자연실업률"] },
  { term: "경제활동참가율", english: "Labor Force Participation Rate", category: "물가·고용", definition: "생산가능인구 중 취업자와 구직자를 합한 경제활동인구의 비율입니다.", related: ["고용률", "실업률", "노동시장"] },
  { term: "비농업고용", english: "Nonfarm Payrolls, NFP", category: "물가·고용", definition: "미국 농업 부문을 제외한 사업체의 취업자 수 변화를 보여주는 대표 고용지표입니다.", related: ["미국 실업률", "임금상승률", "FOMC"] },
  { term: "임금상승률", english: "Wage Growth", category: "물가·고용", definition: "근로자의 임금이 이전 기간보다 얼마나 증가했는지를 나타내며 서비스물가와 소비 여력을 판단할 때 봅니다.", related: ["고용", "서비스물가", "생산성"] },

  { term: "기준금리", english: "Policy Rate, Base Rate", category: "금리·통화", definition: "중앙은행이 경제 전체의 시장금리 방향을 유도하기 위해 정하는 정책금리입니다.", related: ["한국은행", "금융통화위원회", "시장금리"] },
  { term: "명목금리", english: "Nominal Interest Rate", category: "금리·통화", definition: "물가상승을 조정하지 않은 계약상 표시 금리입니다.", related: ["실질금리", "인플레이션", "예금금리"] },
  { term: "실질금리", english: "Real Interest Rate", category: "금리·통화", definition: "명목금리에서 물가상승률을 뺀 것으로 구매력 변화를 반영한 금리입니다.", related: ["명목금리", "물가", "금융여건"] },
  { term: "단기금리", english: "Short-term Interest Rate", category: "금리·통화", definition: "만기가 짧은 금융상품에 적용되는 금리로 중앙은행 정책의 영향을 빠르게 받습니다.", related: ["콜금리", "CD금리", "기준금리"] },
  { term: "장기금리", english: "Long-term Interest Rate", category: "금리·통화", definition: "장기 채권에서 형성되는 금리로 성장률·물가·재정과 미래 정책 기대를 반영합니다.", related: ["국채 10년물", "수익률곡선", "할인율"] },
  { term: "장단기금리차", english: "Yield Spread", category: "금리·통화", definition: "장기금리와 단기금리의 차이로 경기 기대와 금융기관 수익 환경을 읽는 데 사용합니다.", related: ["수익률곡선", "금리역전", "경기침체"] },
  { term: "수익률곡선", english: "Yield Curve", category: "금리·통화", definition: "같은 신용도의 채권을 만기별 금리로 연결한 곡선입니다.", related: ["장단기금리차", "금리역전", "채권"] },
  { term: "통화량", english: "Money Supply, M2", category: "금리·통화", definition: "경제 안에서 현금과 예금 등 지급과 저축에 사용할 수 있는 돈의 규모입니다.", related: ["M1", "M2", "유동성"] },
  { term: "유동성", english: "Liquidity", category: "금리·통화", definition: "자산을 큰 가격 손실 없이 현금으로 바꾸거나 자금을 쉽게 조달할 수 있는 정도입니다.", related: ["통화량", "자금경색", "거래량"] },
  { term: "양적완화", english: "QE, Quantitative Easing", category: "금리·통화", definition: "중앙은행이 국채 등을 대규모 매입해 시중에 유동성을 공급하고 장기금리를 낮추는 정책입니다.", related: ["양적긴축", "자산매입", "중앙은행"] },

  { term: "환율", english: "Exchange Rate", category: "외환·국제", definition: "한 나라의 통화를 다른 나라 통화와 교환하는 비율입니다.", related: ["원/달러", "통화가치", "외환시장"] },
  { term: "원화강세", english: "Korean Won Appreciation", category: "외환·국제", definition: "원화 가치가 올라 같은 달러를 사는 데 필요한 원화가 줄어드는 상태입니다.", related: ["환율하락", "수입물가", "환차익"] },
  { term: "원화약세", english: "Korean Won Depreciation", category: "외환·국제", definition: "원화 가치가 내려 같은 달러를 사는 데 더 많은 원화가 필요한 상태입니다.", related: ["환율상승", "수입물가", "환차손"] },
  { term: "달러인덱스", english: "DXY, U.S. Dollar Index", category: "외환·국제", definition: "유로·엔·파운드 등 주요 통화 바스켓에 대한 미국 달러 가치를 나타내는 지수입니다.", related: ["달러강세", "환율", "미국금리"] },
  { term: "외환보유액", english: "Foreign Exchange Reserves", category: "외환·국제", definition: "중앙은행과 정부가 보유한 외화자산으로 대외 지급과 외환시장 안정에 활용됩니다.", related: ["달러", "대외건전성", "외환위기"] },
  { term: "경상수지", english: "Current Account", category: "외환·국제", definition: "상품·서비스·본원소득·이전소득을 포함한 한 나라의 대외 거래 종합수지입니다.", related: ["무역수지", "서비스수지", "환율"] },
  { term: "자본수지", english: "Capital Account", category: "외환·국제", definition: "자본 이전과 비생산·비금융자산 거래에 따른 국가 간 자금 흐름을 기록한 항목입니다.", related: ["금융계정", "국제수지", "자본이동"] },
  { term: "구매력평가", english: "PPP, Purchasing Power Parity", category: "외환·국제", definition: "같은 상품 바스켓의 가격이 국가 간에 같아지도록 환율이 장기적으로 조정된다는 개념입니다.", related: ["적정환율", "빅맥지수", "물가"] },
  { term: "환헤지", english: "Currency Hedging", category: "외환·국제", definition: "선물환과 파생상품 등을 이용해 환율 변동으로 생길 손익을 줄이는 행위입니다.", related: ["선물환", "환차손", "헤지비용"] },
  { term: "통화스와프", english: "Currency Swap", category: "외환·국제", definition: "두 당사자가 서로 다른 통화를 교환하고 미래에 다시 되돌리기로 하는 계약입니다.", related: ["중앙은행", "외화유동성", "환율안정"] },

  { term: "시가총액", english: "Market Capitalization", category: "주식·투자", definition: "주가에 발행주식 수를 곱한 값으로 시장이 평가하는 기업의 전체 지분가치입니다.", related: ["주가", "대형주", "지수"] },
  { term: "주가수익비율", english: "PER, Price Earnings Ratio", category: "주식·투자", definition: "주가를 주당순이익으로 나눈 값으로 이익 대비 주가 수준을 비교할 때 사용합니다.", related: ["EPS", "밸류에이션", "성장률"] },
  { term: "주가순자산비율", english: "PBR, Price Book-value Ratio", category: "주식·투자", definition: "주가를 주당순자산으로 나눈 값으로 장부가치 대비 시장평가를 보여줍니다.", related: ["BPS", "ROE", "자산가치"] },
  { term: "자기자본이익률", english: "ROE, Return on Equity", category: "주식·투자", definition: "기업이 주주자본을 사용해 얼마의 순이익을 만들었는지를 나타내는 비율입니다.", related: ["순이익", "자기자본", "PBR"] },
  { term: "주당순이익", english: "EPS, Earnings Per Share", category: "주식·투자", definition: "기업의 순이익을 유통 주식 수로 나눈 주당 이익입니다.", related: ["PER", "순이익", "실적"] },
  { term: "배당수익률", english: "Dividend Yield", category: "주식·투자", definition: "주당 배당금을 현재 주가로 나눈 비율로 주가 대비 배당 현금수익을 보여줍니다.", related: ["배당금", "배당성향", "주주환원"] },
  { term: "밸류에이션", english: "Valuation", category: "주식·투자", definition: "기업의 이익·자산·현금흐름에 비해 현재 가격이 어느 수준인지 평가하는 과정입니다.", related: ["PER", "PBR", "할인율"] },
  { term: "유상증자", english: "Rights Offering", category: "주식·투자", definition: "기업이 새 주식을 발행해 투자자에게 판매하고 자본금을 늘리는 방식입니다.", related: ["주식희석", "자본조달", "신주"] },
  { term: "무상증자", english: "Bonus Issue", category: "주식·투자", definition: "기업이 보유한 잉여금을 자본금으로 옮기고 주주에게 새 주식을 무상 배정하는 방식입니다.", related: ["권리락", "주식수", "자본금"] },
  { term: "자사주", english: "Treasury Stock", category: "주식·투자", definition: "회사가 자기 회사의 발행주식을 다시 사서 보유하는 주식입니다.", related: ["자사주매입", "자사주소각", "주주환원"] },

  { term: "국채", english: "Government Bond", category: "채권·신용", definition: "정부가 재정자금을 조달하기 위해 발행하는 채권입니다.", related: ["국고채", "국채금리", "안전자산"] },
  { term: "회사채", english: "Corporate Bond", category: "채권·신용", definition: "기업이 사업자금을 빌리기 위해 발행하는 채권입니다.", related: ["신용등급", "신용스프레드", "국채"] },
  { term: "채권가격", english: "Bond Price", category: "채권·신용", definition: "시장에서 거래되는 채권의 가격으로 일반적으로 시장금리와 반대로 움직입니다.", related: ["채권금리", "쿠폰", "만기"] },
  { term: "채권금리", english: "Bond Yield", category: "채권·신용", definition: "채권 투자로 기대할 수 있는 수익률이며 가격이 내려가면 대체로 상승합니다.", related: ["채권가격", "국채금리", "수익률곡선"] },
  { term: "듀레이션", english: "Duration", category: "채권·신용", definition: "채권 현금흐름의 평균 회수기간이자 금리 변화에 대한 가격 민감도를 나타내는 지표입니다.", related: ["금리위험", "만기", "채권가격"] },
  { term: "신용등급", english: "Credit Rating", category: "채권·신용", definition: "채무자가 원금과 이자를 제때 갚을 능력을 등급으로 평가한 것입니다.", related: ["부도위험", "회사채", "신용평가사"] },
  { term: "신용스프레드", english: "Credit Spread", category: "채권·신용", definition: "회사채 금리와 국채 금리의 차이로 기업 위험에 대해 시장이 요구하는 추가 보상입니다.", related: ["회사채", "국채", "자금경색"] },
  { term: "부도율", english: "Default Rate", category: "채권·신용", definition: "채무자가 약속한 원리금을 갚지 못한 비율입니다.", related: ["신용위험", "연체율", "회수율"] },
  { term: "하이일드채권", english: "High-yield Bond", category: "채권·신용", definition: "신용등급이 낮아 부도위험이 높은 대신 금리가 높은 회사채입니다.", related: ["정크본드", "신용스프레드", "위험선호"] },
  { term: "전환사채", english: "CB, Convertible Bond", category: "채권·신용", definition: "일정 조건에 따라 발행기업의 주식으로 바꿀 수 있는 권리가 붙은 채권입니다.", related: ["신주인수권", "주식희석", "회사채"] },

  { term: "선물", english: "Futures", category: "파생·위험", definition: "미래의 정해진 시점에 자산을 미리 정한 가격으로 사고팔기로 하는 표준화 계약입니다.", related: ["만기", "증거금", "헤지"] },
  { term: "옵션", english: "Options", category: "파생·위험", definition: "정해진 기간 안에 자산을 특정 가격으로 사고팔 수 있는 권리입니다.", related: ["콜옵션", "풋옵션", "프리미엄"] },
  { term: "콜옵션", english: "Call Option", category: "파생·위험", definition: "기초자산을 약정가격에 살 수 있는 권리입니다.", related: ["옵션", "행사가격", "상승전망"] },
  { term: "풋옵션", english: "Put Option", category: "파생·위험", definition: "기초자산을 약정가격에 팔 수 있는 권리입니다.", related: ["옵션", "헤지", "하락전망"] },
  { term: "레버리지", english: "Leverage", category: "파생·위험", definition: "차입이나 파생상품을 이용해 자기자본보다 큰 투자 노출을 만드는 방식입니다.", related: ["부채", "수익확대", "손실확대"] },
  { term: "마진콜", english: "Margin Call", category: "파생·위험", definition: "손실로 증거금이 부족해졌을 때 거래기관이 추가 자금 납입을 요구하는 것입니다.", related: ["증거금", "강제청산", "레버리지"] },
  { term: "공매도", english: "Short Selling", category: "파생·위험", definition: "주식을 빌려 먼저 판 뒤 가격이 내려가면 다시 사서 갚는 거래입니다.", related: ["대차거래", "숏커버", "하락베팅"] },
  { term: "변동성", english: "Volatility", category: "파생·위험", definition: "일정 기간 자산 가격이 얼마나 크게 오르내리는지를 나타냅니다.", related: ["위험", "표준편차", "VIX"] },
  { term: "공포지수", english: "VIX", category: "파생·위험", definition: "S&P 500 옵션 가격에서 계산한 향후 약 30일의 예상 변동성 지수입니다.", related: ["변동성", "위험회피", "옵션"] },
  { term: "베타", english: "Beta", category: "파생·위험", definition: "특정 자산이 시장 전체 움직임에 얼마나 민감하게 반응하는지를 나타내는 값입니다.", related: ["시장위험", "알파", "변동성"] },

  { term: "매출", english: "Revenue, Sales", category: "기업·회계", definition: "기업이 상품과 서비스를 판매해 벌어들인 총수입입니다.", related: ["영업이익", "매출성장률", "판매량"] },
  { term: "영업이익", english: "Operating Profit", category: "기업·회계", definition: "매출에서 제품 원가와 판매·관리비 등 본업 비용을 뺀 이익입니다.", related: ["매출", "영업이익률", "순이익"] },
  { term: "순이익", english: "Net Income", category: "기업·회계", definition: "영업외손익과 이자·세금까지 모두 반영한 뒤 최종적으로 남은 이익입니다.", related: ["영업이익", "EPS", "법인세"] },
  { term: "상각전영업이익", english: "EBITDA", category: "기업·회계", definition: "이자·세금·감가상각비를 차감하기 전 이익으로 영업현금 창출력을 비교할 때 활용합니다.", related: ["영업이익", "감가상각", "현금흐름"] },
  { term: "영업이익률", english: "Operating Margin", category: "기업·회계", definition: "매출 가운데 영업이익이 차지하는 비율로 본업의 수익성을 보여줍니다.", related: ["영업이익", "마진", "원가"] },
  { term: "부채비율", english: "Debt-to-Equity Ratio", category: "기업·회계", definition: "부채를 자기자본으로 나눈 비율로 재무 레버리지 수준을 보여줍니다.", related: ["자기자본", "차입금", "재무건전성"] },
  { term: "영업현금흐름", english: "Operating Cash Flow", category: "기업·회계", definition: "기업의 본업 활동에서 실제로 들어오고 나간 현금의 순액입니다.", related: ["순이익", "현금흐름표", "운전자본"] },
  { term: "잉여현금흐름", english: "FCF, Free Cash Flow", category: "기업·회계", definition: "영업현금흐름에서 사업 유지와 성장을 위한 자본적지출을 뺀 현금입니다.", related: ["배당", "자사주", "CAPEX"] },
  { term: "재고자산", english: "Inventory", category: "기업·회계", definition: "판매를 위해 보유한 상품·제품·원재료 등 기업의 재고입니다.", related: ["재고회전율", "재고순환", "운전자본"] },
  { term: "자본적지출", english: "CAPEX, Capital Expenditure", category: "기업·회계", definition: "공장·장비·데이터센터처럼 장기간 사용할 자산을 취득하거나 개선하는 지출입니다.", related: ["감가상각", "설비투자", "잉여현금흐름"] },

  { term: "수출", english: "Exports", category: "무역·산업", definition: "국내에서 생산한 상품과 서비스를 해외에 판매하는 것입니다.", related: ["수입", "무역수지", "환율"] },
  { term: "수입", english: "Imports", category: "무역·산업", definition: "해외에서 생산한 상품과 서비스를 국내로 들여오는 것입니다.", related: ["수출", "수입물가", "환율"] },
  { term: "무역수지", english: "Trade Balance", category: "무역·산업", definition: "일정 기간 상품 수출액에서 상품 수입액을 뺀 값입니다.", related: ["경상수지", "수출", "수입"] },
  { term: "관세", english: "Tariff", category: "무역·산업", definition: "정부가 국경을 통과하는 수입품이나 수출품에 부과하는 세금입니다.", related: ["무역분쟁", "보호무역", "수입가격"] },
  { term: "공급망", english: "Supply Chain", category: "무역·산업", definition: "원재료 조달부터 생산·운송·판매까지 제품이 소비자에게 가는 전체 연결망입니다.", related: ["물류", "재고", "공급충격"] },
  { term: "비교우위", english: "Comparative Advantage", category: "무역·산업", definition: "다른 나라보다 상대적으로 낮은 기회비용으로 생산할 수 있는 분야에 특화하는 원리입니다.", related: ["국제무역", "기회비용", "분업"] },
  { term: "교역조건", english: "Terms of Trade", category: "무역·산업", definition: "수출품 가격을 수입품 가격으로 나눈 비율로 무역을 통해 얻는 구매력 변화를 보여줍니다.", related: ["수출가격", "수입가격", "GNI"] },
  { term: "반도체 사이클", english: "Semiconductor Cycle", category: "무역·산업", definition: "반도체 수요·재고·가격·설비투자가 상승과 하락을 반복하는 산업 주기입니다.", related: ["메모리 가격", "재고", "수출"] },
  { term: "재고순환", english: "Inventory Cycle", category: "무역·산업", definition: "기업이 수요 변화에 맞춰 재고를 늘리고 줄이면서 생산과 경기가 변하는 흐름입니다.", related: ["재고자산", "생산", "경기선행"] },
  { term: "구매관리자지수", english: "PMI, Purchasing Managers Index", category: "무역·산업", definition: "기업 구매담당자 설문으로 생산·주문·고용의 확장과 위축을 빠르게 보여주는 지수입니다.", related: ["제조업", "서비스업", "경기선행지표"] },

  { term: "주택담보인정비율", english: "LTV, Loan to Value", category: "부동산·가계", definition: "주택가격 대비 주택담보대출 가능 금액의 비율입니다.", related: ["담보가치", "주택담보대출", "DSR"] },
  { term: "총부채상환비율", english: "DTI, Debt to Income", category: "부동산·가계", definition: "연소득에서 주택담보대출 원리금과 기타 대출 이자가 차지하는 비율입니다.", related: ["DSR", "소득", "대출규제"] },
  { term: "총부채원리금상환비율", english: "DSR, Debt Service Ratio", category: "부동산·가계", definition: "연소득에서 모든 금융대출의 연간 원리금 상환액이 차지하는 비율입니다.", related: ["DTI", "가계부채", "대출한도"] },
  { term: "가계부채", english: "Household Debt", category: "부동산·가계", definition: "가계가 금융기관 등에 갚아야 할 대출과 신용채무의 총액입니다.", related: ["가계신용", "금리", "소비"] },
  { term: "주택담보대출", english: "Mortgage Loan", category: "부동산·가계", definition: "주택을 담보로 금융기관에서 빌리는 대출입니다.", related: ["LTV", "고정금리", "변동금리"] },
  { term: "전세가율", english: "Jeonse Price Ratio", category: "부동산·가계", definition: "주택 매매가격 대비 전세가격의 비율입니다.", related: ["전세가격", "매매가격", "갭투자"] },
  { term: "공시가격", english: "Officially Assessed Price", category: "부동산·가계", definition: "정부가 조사·산정해 공시하는 부동산 가격으로 보유세와 각종 행정 기준에 활용됩니다.", related: ["실거래가", "기준시가", "보유세"] },
  { term: "기준시가", english: "Standard Value", category: "부동산·가계", definition: "세금을 계산하기 위해 국세청 등이 정한 부동산과 자산의 평가가격입니다.", related: ["공시가격", "양도소득세", "상속세"] },
  { term: "부동산 PF", english: "Project Financing", category: "부동산·가계", definition: "개발사업 자체의 미래 현금흐름을 바탕으로 자금을 조달하는 금융방식입니다.", related: ["브리지론", "시행사", "신용위험"] },
  { term: "역전세", english: "Reverse Jeonse", category: "부동산·가계", definition: "새 전세가격이 기존 보증금보다 낮아 집주인이 보증금 반환에 어려움을 겪는 상황입니다.", related: ["전세보증금", "깡통전세", "전세가율"] },

  { term: "서부텍사스유", english: "WTI, West Texas Intermediate", category: "원자재·에너지", definition: "미국에서 거래되는 대표 원유 가격 기준 중 하나입니다.", related: ["브렌트유", "국제유가", "원유선물"] },
  { term: "브렌트유", english: "Brent Crude", category: "원자재·에너지", definition: "북해산 원유를 기준으로 한 국제 원유 가격의 대표 지표입니다.", related: ["WTI", "두바이유", "국제유가"] },
  { term: "석유수출국기구", english: "OPEC", category: "원자재·에너지", definition: "주요 산유국이 석유 생산정책을 조정하기 위해 만든 국제기구입니다.", related: ["감산", "원유공급", "OPEC+"] },
  { term: "금", english: "Gold", category: "원자재·에너지", definition: "귀금속이자 달러·실질금리·지정학 위험에 반응하는 대표적인 가치저장 자산입니다.", related: ["안전자산", "실질금리", "달러"] },
  { term: "구리", english: "Copper", category: "원자재·에너지", definition: "건설과 제조업에 널리 쓰여 글로벌 경기 흐름을 보여주는 산업금속입니다.", related: ["중국경기", "제조업", "원자재"] },
  { term: "천연가스", english: "Natural Gas", category: "원자재·에너지", definition: "발전·난방·산업용으로 사용되는 에너지원으로 날씨와 저장량, 지정학에 민감합니다.", related: ["LNG", "에너지", "전력가격"] },
  { term: "원자재지수", english: "Commodity Index", category: "원자재·에너지", definition: "에너지·금속·농산물 등 여러 원자재 가격을 묶어 나타낸 지수입니다.", related: ["인플레이션", "달러", "선물"] },
  { term: "정제마진", english: "Refining Margin", category: "원자재·에너지", definition: "정유사가 원유를 휘발유·경유 등으로 정제해 얻는 제품가격과 원료비의 차이입니다.", related: ["정유사", "유가", "석유제품"] },
  { term: "국제유가", english: "Crude Oil Price", category: "원자재·에너지", definition: "국제시장에서 거래되는 원유 가격으로 물가와 운송비, 기업비용에 폭넓게 영향을 줍니다.", related: ["WTI", "브렌트유", "인플레이션"] },
  { term: "안전자산", english: "Safe-haven Asset", category: "원자재·에너지", definition: "경제·금융 불안 때 상대적으로 가치 보존이 기대되어 자금이 몰리는 자산입니다.", related: ["금", "달러", "국채"] },

  { term: "재정정책", english: "Fiscal Policy", category: "정책·제도", definition: "정부가 세금과 지출을 조정해 경기와 소득분배에 영향을 주는 정책입니다.", related: ["정부지출", "조세", "재정수지"] },
  { term: "통화정책", english: "Monetary Policy", category: "정책·제도", definition: "중앙은행이 금리와 통화량을 조정해 물가와 경기에 영향을 주는 정책입니다.", related: ["기준금리", "양적완화", "중앙은행"] },
  { term: "추가경정예산", english: "Supplementary Budget", category: "정책·제도", definition: "본예산이 확정된 뒤 경기 대응이나 재난 등 추가 필요에 따라 편성하는 예산입니다.", related: ["정부지출", "국채", "재정정책"] },
  { term: "국가채무", english: "Government Debt", category: "정책·제도", definition: "정부가 갚아야 할 국채와 차입금 등 확정된 채무입니다.", related: ["국채", "재정수지", "채무비율"] },
  { term: "재정수지", english: "Fiscal Balance", category: "정책·제도", definition: "정부의 총수입과 총지출의 차이로 흑자 또는 적자로 나타납니다.", related: ["관리재정수지", "통합재정수지", "국가채무"] },
  { term: "조세부담률", english: "Tax Burden Ratio", category: "정책·제도", definition: "국민이 낸 국세와 지방세가 GDP에서 차지하는 비율입니다.", related: ["국민부담률", "세수", "GDP"] },
  { term: "중앙은행", english: "Central Bank", category: "정책·제도", definition: "통화 발행과 통화정책, 금융안정을 담당하는 국가의 핵심 금융기관입니다.", related: ["한국은행", "연방준비제도", "기준금리"] },
  { term: "연방공개시장위원회", english: "FOMC", category: "정책·제도", definition: "미국 연방준비제도에서 기준금리와 자산정책을 결정하는 회의체입니다.", related: ["연준", "점도표", "연방기금금리"] },
  { term: "금융통화위원회", english: "Monetary Policy Board", category: "정책·제도", definition: "한국은행의 기준금리와 주요 통화신용정책을 심의·의결하는 기구입니다.", related: ["한국은행", "기준금리", "통화정책방향"] },
  { term: "정책금리", english: "Policy Interest Rate", category: "정책·제도", definition: "중앙은행이 통화정책 목표를 달성하기 위해 직접 설정하거나 유도하는 금리입니다.", related: ["기준금리", "시장금리", "통화정책"] },

  { term: "위험선호", english: "Risk-on", category: "시장심리·자금", definition: "투자자가 변동성을 감수하고 주식·회사채·신흥국 자산 등 기대수익이 높은 자산을 사려는 분위기입니다.", related: ["위험회피", "VIX", "신흥국"] },
  { term: "위험회피", english: "Risk-off", category: "시장심리·자금", definition: "불확실성이 커져 투자자가 현금·국채·달러 등 방어자산을 선호하는 분위기입니다.", related: ["안전자산", "VIX", "달러강세"] },
  { term: "외국인 수급", english: "Foreign Investor Flow", category: "시장심리·자금", definition: "외국인 투자자의 국내 주식과 채권 순매수·순매도 흐름입니다.", related: ["환율", "KOSPI", "자금유출입"] },
  { term: "기관 수급", english: "Institutional Flow", category: "시장심리·자금", definition: "연기금·보험·투자신탁 등 기관투자자의 매매 흐름입니다.", related: ["연기금", "프로그램매매", "순매수"] },
  { term: "개인 수급", english: "Retail Investor Flow", category: "시장심리·자금", definition: "개인투자자의 주식시장 순매수·순매도 흐름입니다.", related: ["예탁금", "신용융자", "거래대금"] },
  { term: "펀드플로", english: "Fund Flow", category: "시장심리·자금", definition: "펀드와 ETF 등 투자상품으로 들어오고 나가는 자금 흐름입니다.", related: ["자금유입", "환매", "ETF"] },
  { term: "패시브자금", english: "Passive Fund", category: "시장심리·자금", definition: "특정 지수를 그대로 추종하도록 운용되는 자금입니다.", related: ["인덱스펀드", "ETF", "리밸런싱"] },
  { term: "액티브자금", english: "Active Fund", category: "시장심리·자금", definition: "운용자가 종목과 비중을 선택해 기준지수보다 높은 수익을 추구하는 자금입니다.", related: ["펀드매니저", "알파", "벤치마크"] },
  { term: "자금경색", english: "Credit Crunch", category: "시장심리·자금", definition: "금융기관과 시장에서 돈을 빌리기 어려워지고 자금조달 비용이 급격히 오르는 상태입니다.", related: ["유동성", "신용스프레드", "부도위험"] },
  { term: "디레버리징", english: "Deleveraging", category: "시장심리·자금", definition: "가계·기업·투자자가 부채와 투자 노출을 줄이는 과정입니다.", related: ["레버리지", "강제매도", "부채축소"] },

  { term: "암호화폐", english: "Cryptocurrency", category: "디지털경제", definition: "암호기술과 분산원장을 이용해 발행·이전되는 디지털 자산입니다.", related: ["비트코인", "블록체인", "가상자산"] },
  { term: "블록체인", english: "Blockchain", category: "디지털경제", definition: "거래기록을 여러 참여자가 공유하고 검증하는 분산형 데이터 저장기술입니다.", related: ["분산원장", "암호화폐", "스마트계약"] },
  { term: "스테이블코인", english: "Stablecoin", category: "디지털경제", definition: "달러 같은 법정통화나 자산에 가치를 연동하도록 설계한 디지털 토큰입니다.", related: ["준비자산", "가상자산", "결제"] },
  { term: "중앙은행 디지털화폐", english: "CBDC", category: "디지털경제", definition: "중앙은행이 직접 발행하는 전자 형태의 법정통화입니다.", related: ["중앙은행", "디지털원화", "결제시스템"] },
  { term: "핀테크", english: "Fintech", category: "디지털경제", definition: "금융과 기술을 결합해 결제·송금·투자·대출 서비스를 혁신하는 산업입니다.", related: ["간편결제", "인터넷은행", "로보어드바이저"] },
  { term: "토큰화", english: "Tokenization", category: "디지털경제", definition: "부동산·채권·미술품 등의 권리를 블록체인상 디지털 토큰으로 표현하는 방식입니다.", related: ["증권형토큰", "블록체인", "조각투자"] },
  { term: "네트워크효과", english: "Network Effect", category: "디지털경제", definition: "사용자가 늘어날수록 서비스의 가치가 더 커지는 현상입니다.", related: ["플랫폼", "규모의경제", "진입장벽"] },
  { term: "플랫폼경제", english: "Platform Economy", category: "디지털경제", definition: "디지털 플랫폼이 생산자와 소비자를 연결하며 거래와 데이터를 조직하는 경제구조입니다.", related: ["양면시장", "네트워크효과", "수수료"] },
  { term: "인공지능 자본지출", english: "AI CAPEX", category: "디지털경제", definition: "기업이 AI 모델·반도체·데이터센터·전력설비에 투자하는 자본적지출입니다.", related: ["데이터센터", "GPU", "CAPEX"] },
  { term: "데이터센터", english: "Data Center", category: "디지털경제", definition: "서버와 저장장치, 네트워크 설비를 모아 대규모 데이터를 처리·보관하는 시설입니다.", related: ["클라우드", "AI", "전력수요"] }
];
