export const indicatorCountries = [
  { id: "KOR", label: "한국", shortLabel: "한국" },
  { id: "WLD", label: "세계", shortLabel: "세계" },
  { id: "USA", label: "미국", shortLabel: "미국" },
  { id: "JPN", label: "일본", shortLabel: "일본" },
  { id: "CHN", label: "중국", shortLabel: "중국" },
  { id: "DEU", label: "독일", shortLabel: "독일" }
];

export const indicatorCategories = [
  { id: "all", label: "전체" },
  { id: "population", label: "인구" },
  { id: "economy", label: "성장·산업" },
  { id: "labor", label: "노동" },
  { id: "health", label: "건강" },
  { id: "education", label: "교육·기술" },
  { id: "environment", label: "환경·에너지" },
  { id: "society", label: "사회·연결" }
];

export const indicatorDefinitions = [
  {
    id: "fertility",
    code: "SP.DYN.TFRT.IN",
    category: "population",
    name: "합계출산율",
    shortName: "출산율",
    unit: "명",
    precision: 2,
    description: "여성 1명이 평생 낳을 것으로 예상되는 평균 자녀 수입니다.",
    reading: "세대 규모가 장기적으로 유지되는 대체출산율은 대략 2.1명입니다.",
    caution: "출생아 수와 다른 지표이며 혼인, 주거, 고용, 돌봄 여건을 함께 봐야 합니다."
  },
  {
    id: "population-growth",
    code: "SP.POP.GROW",
    category: "population",
    name: "인구 증가율",
    shortName: "인구 증가",
    unit: "%",
    precision: 2,
    description: "전년과 비교해 총인구가 얼마나 늘거나 줄었는지 보여줍니다.",
    reading: "0% 아래면 출생·사망과 국제이동을 합친 총인구가 감소했다는 뜻입니다.",
    caution: "출산율이 낮아도 이민이 많으면 인구는 증가할 수 있습니다."
  },
  {
    id: "older-population",
    code: "SP.POP.65UP.TO.ZS",
    category: "population",
    name: "65세 이상 인구 비중",
    shortName: "고령인구",
    unit: "%",
    precision: 1,
    description: "전체 인구에서 65세 이상이 차지하는 비율입니다.",
    reading: "높아질수록 연금·의료·돌봄과 생산가능인구 부담이 커질 수 있습니다.",
    caution: "건강수명과 고령층 고용률에 따라 경제적 영향은 달라집니다."
  },
  {
    id: "life-expectancy",
    code: "SP.DYN.LE00.IN",
    category: "population",
    name: "기대수명",
    shortName: "기대수명",
    unit: "년",
    precision: 1,
    description: "현재의 연령별 사망률이 이어질 때 신생아가 살 것으로 기대되는 기간입니다.",
    reading: "보건, 소득, 생활환경이 함께 반영되는 장기 생활 수준 지표입니다.",
    caution: "건강하게 사는 기간인 건강수명과는 차이가 있습니다."
  },
  {
    id: "gdp-per-capita",
    code: "NY.GDP.PCAP.CD",
    category: "economy",
    name: "1인당 GDP",
    shortName: "1인당 GDP",
    unit: "달러",
    precision: 0,
    format: "currency",
    description: "국내총생산을 인구로 나눈 명목 달러 기준 값입니다.",
    reading: "국가의 평균적인 생산·소득 수준을 비교하는 가장 널리 쓰이는 지표입니다.",
    caution: "환율에 따라 크게 움직이며 개인의 실제 소득이나 분배 상태를 직접 뜻하지 않습니다."
  },
  {
    id: "gdp-growth",
    code: "NY.GDP.MKTP.KD.ZG",
    category: "economy",
    name: "실질 GDP 성장률",
    shortName: "경제성장률",
    unit: "%",
    precision: 2,
    description: "물가 영향을 제거한 경제 규모가 전년보다 얼마나 변했는지 보여줍니다.",
    reading: "플러스는 경제 확장, 마이너스는 실질 생산 감소를 뜻합니다.",
    caution: "한 해의 성장률만으로 장기 경쟁력이나 체감경기를 판단하면 안 됩니다."
  },
  {
    id: "manufacturing-share",
    code: "NV.IND.MANF.ZS",
    category: "economy",
    name: "제조업 부가가치 비중",
    shortName: "제조업 비중",
    unit: "%",
    precision: 1,
    description: "GDP에서 제조업이 만들어낸 부가가치의 비중입니다.",
    reading: "한국 경제가 수출 제조업과 세계 교역에 얼마나 민감한지 보여줍니다.",
    caution: "비중이 높다고 무조건 좋은 것은 아니며 서비스업 생산성과 함께 봐야 합니다."
  },
  {
    id: "trade-share",
    code: "NE.TRD.GNFS.ZS",
    category: "economy",
    name: "무역의존도",
    shortName: "무역의존도",
    unit: "%",
    precision: 1,
    description: "상품·서비스 수출과 수입의 합을 GDP와 비교한 비율입니다.",
    reading: "높을수록 해외 수요, 환율, 공급망 변화가 국내 경제에 빠르게 전달됩니다.",
    caution: "국가 규모가 작을수록 구조적으로 높아지는 경향이 있습니다."
  },
  {
    id: "unemployment",
    code: "SL.UEM.TOTL.ZS",
    category: "labor",
    name: "실업률",
    shortName: "실업률",
    unit: "%",
    precision: 1,
    description: "일할 의사와 능력이 있고 구직 중인 사람 중 일자리가 없는 비율입니다.",
    reading: "경기 냉각 시 대체로 상승하지만 노동시장 제도에 따라 국가 비교가 달라집니다.",
    caution: "구직을 포기한 사람은 실업자에서 제외될 수 있어 고용률과 같이 봐야 합니다."
  },
  {
    id: "labor-participation",
    code: "SL.TLF.CACT.ZS",
    category: "labor",
    name: "경제활동참가율",
    shortName: "경제활동 참가",
    unit: "%",
    precision: 1,
    description: "15세 이상 인구 중 취업했거나 적극적으로 구직 중인 비율입니다.",
    reading: "노동시장에 실제로 참여하는 인구의 크기를 보여줍니다.",
    caution: "고령화와 학업 기간, 군 복무 등 인구구조의 영향을 받습니다."
  },
  {
    id: "female-participation",
    code: "SL.TLF.CACT.FE.ZS",
    category: "labor",
    name: "여성 경제활동참가율",
    shortName: "여성 경제활동",
    unit: "%",
    precision: 1,
    description: "15세 이상 여성 중 취업했거나 적극적으로 구직 중인 비율입니다.",
    reading: "돌봄, 경력단절, 일자리 접근성과 노동력 활용 정도를 함께 보여줍니다.",
    caution: "참가율만으로 임금 격차나 일자리의 질을 알 수는 없습니다."
  },
  {
    id: "youth-unemployment",
    code: "SL.UEM.1524.ZS",
    category: "labor",
    name: "청년 실업률",
    shortName: "청년 실업",
    unit: "%",
    precision: 1,
    description: "15~24세 경제활동인구 중 일자리를 찾지 못한 비율입니다.",
    reading: "청년층이 교육에서 일자리로 이동하는 과정의 어려움을 보여줍니다.",
    caution: "진학률과 병역 제도가 달라 국가 간 단순 비교에는 주의가 필요합니다."
  },
  {
    id: "health-spending",
    code: "SH.XPD.CHEX.GD.ZS",
    category: "health",
    name: "의료비 지출 비중",
    shortName: "의료비 지출",
    unit: "% GDP",
    precision: 1,
    description: "국가 전체 경상의료비가 GDP에서 차지하는 비율입니다.",
    reading: "보건의료에 투입되는 자원 규모를 경제 크기와 비교합니다.",
    caution: "비중이 높다고 의료 성과나 접근성이 반드시 좋은 것은 아닙니다."
  },
  {
    id: "infant-mortality",
    code: "SP.DYN.IMRT.IN",
    category: "health",
    name: "영아 사망률",
    shortName: "영아 사망",
    unit: "명/출생 1천명",
    precision: 1,
    description: "출생아 1천 명 중 만 1세 이전에 사망하는 아이의 수입니다.",
    reading: "산모·영아 의료, 영양, 위생과 의료 접근성을 종합적으로 반영합니다.",
    caution: "낮을수록 좋은 지표이며 국가별 등록 체계 차이가 있을 수 있습니다."
  },
  {
    id: "physicians",
    code: "SH.MED.PHYS.ZS",
    category: "health",
    name: "의사 수",
    shortName: "의사 수",
    unit: "명/인구 1천명",
    precision: 2,
    description: "인구 1천 명당 활동 의사 수입니다.",
    reading: "의료 인력 공급의 기본 규모를 국가 간 비교할 수 있습니다.",
    caution: "지역 분포, 진료과, 근무시간과 의료 전달체계는 이 숫자에 드러나지 않습니다."
  },
  {
    id: "under-five-mortality",
    code: "SH.DYN.MORT",
    category: "health",
    name: "5세 미만 사망률",
    shortName: "5세 미만 사망",
    unit: "명/출생 1천명",
    precision: 1,
    description: "출생아 1천 명 중 만 5세 이전에 사망할 확률입니다.",
    reading: "아동 보건과 기초 의료·생활환경을 함께 보여주는 국제 비교 지표입니다.",
    caution: "낮을수록 좋은 지표이며 추정 방법과 등록 품질을 확인해야 합니다."
  },
  {
    id: "tertiary-enrollment",
    code: "SE.TER.ENRR",
    category: "education",
    name: "고등교육 총취학률",
    shortName: "고등교육 취학",
    unit: "%",
    precision: 1,
    description: "대학 연령대 인구 대비 실제 고등교육 재학생의 비율입니다.",
    reading: "연령과 관계없이 재학생을 포함해 100%를 넘을 수도 있습니다.",
    caution: "교육의 질, 전공 구성, 졸업 후 취업 성과까지 뜻하지는 않습니다."
  },
  {
    id: "research-development",
    code: "GB.XPD.RSDV.GD.ZS",
    category: "education",
    name: "연구개발 지출",
    shortName: "R&D 지출",
    unit: "% GDP",
    precision: 2,
    description: "정부·기업·대학의 연구개발비를 GDP와 비교한 비율입니다.",
    reading: "미래 기술과 생산성에 투입하는 자원의 크기를 보여줍니다.",
    caution: "지출 규모가 실제 혁신 성과로 이어지는지는 특허·사업화와 함께 봐야 합니다."
  },
  {
    id: "internet-use",
    code: "IT.NET.USER.ZS",
    category: "education",
    name: "인터넷 이용률",
    shortName: "인터넷 이용",
    unit: "%",
    precision: 1,
    description: "최근 일정 기간 인터넷을 사용한 인구의 비율입니다.",
    reading: "디지털 접근성과 온라인 경제 참여의 기본 조건을 보여줍니다.",
    caution: "접속 속도, 비용, 활용 능력의 격차는 별도로 확인해야 합니다."
  },
  {
    id: "high-tech-exports",
    code: "TX.VAL.TECH.MF.ZS",
    category: "education",
    name: "첨단기술 수출 비중",
    shortName: "첨단기술 수출",
    unit: "% 제조업 수출",
    precision: 1,
    description: "제조업 수출에서 항공·컴퓨터·전자·의약 등 첨단기술 제품의 비중입니다.",
    reading: "수출 품목의 기술집약도와 산업 경쟁력을 살펴보는 지표입니다.",
    caution: "해외 부품을 조립한 수출도 포함될 수 있어 국내 부가가치와 구분해야 합니다."
  },
  {
    id: "co2-per-capita",
    code: "EN.GHG.CO2.PC.CE.AR5",
    category: "environment",
    name: "1인당 이산화탄소 배출",
    shortName: "1인당 CO₂",
    unit: "tCO₂e",
    precision: 1,
    description: "토지이용 변화를 제외한 1인당 연간 이산화탄소 배출량입니다.",
    reading: "생활과 산업 구조가 기후에 주는 부담을 인구 규모와 나눠 비교합니다.",
    caution: "해외에서 생산해 수입한 상품의 배출은 생산국에 잡힐 수 있습니다."
  },
  {
    id: "renewable-energy",
    code: "EG.FEC.RNEW.ZS",
    category: "environment",
    name: "재생에너지 소비 비중",
    shortName: "재생에너지",
    unit: "%",
    precision: 1,
    description: "최종 에너지 소비에서 재생에너지가 차지하는 비율입니다.",
    reading: "에너지 전환 수준과 화석연료 의존도를 비교할 수 있습니다.",
    caution: "전력 생산 비중과 다른 개념이며 전통 바이오매스가 포함될 수 있습니다."
  },
  {
    id: "energy-use",
    code: "EG.USE.PCAP.KG.OE",
    category: "environment",
    name: "1인당 에너지 사용량",
    shortName: "에너지 사용",
    unit: "kg 석유환산",
    precision: 0,
    description: "한 사람이 1년 동안 사용하는 1차 에너지를 석유환산 kg으로 나타냅니다.",
    reading: "산업 구조, 소득 수준, 기후와 에너지 효율의 영향을 함께 받습니다.",
    caution: "높고 낮음만으로 효율을 판단하지 말고 GDP 대비 에너지 사용과 같이 봐야 합니다."
  },
  {
    id: "pm25",
    code: "EN.ATM.PM25.MC.M3",
    category: "environment",
    name: "초미세먼지 노출",
    shortName: "PM2.5 노출",
    unit: "㎍/㎥",
    precision: 1,
    description: "인구가 가중된 연평균 PM2.5 노출 농도입니다.",
    reading: "낮을수록 대기오염으로 인한 건강 부담이 작다는 뜻입니다.",
    caution: "전국 연평균이므로 특정 도시나 계절의 고농도 상황과 다를 수 있습니다."
  },
  {
    id: "gini",
    code: "SI.POV.GINI",
    category: "society",
    name: "지니계수",
    shortName: "소득 불평등",
    unit: "점",
    precision: 1,
    description: "소득 분배의 불평등 정도를 0~100으로 나타냅니다.",
    reading: "0에 가까울수록 균등하고 100에 가까울수록 소득이 한쪽에 집중됩니다.",
    caution: "조사연도와 세전·세후 기준이 달라 국가별 기준연도를 반드시 확인해야 합니다."
  },
  {
    id: "urban-population",
    code: "SP.URB.TOTL.IN.ZS",
    category: "society",
    name: "도시 인구 비중",
    shortName: "도시화율",
    unit: "%",
    precision: 1,
    description: "전체 인구 중 각 국가 기준의 도시 지역에 사는 비율입니다.",
    reading: "주거, 교통, 지역 격차와 서비스 산업 구조를 이해하는 기초 지표입니다.",
    caution: "국가마다 도시를 정의하는 기준이 달라 절대 비교에는 한계가 있습니다."
  },
  {
    id: "fixed-broadband",
    code: "IT.NET.BBND.P2",
    category: "society",
    name: "고정 광대역 가입",
    shortName: "고정 인터넷",
    unit: "회선/100명",
    precision: 1,
    description: "인구 100명당 고정 초고속인터넷 가입 회선 수입니다.",
    reading: "가정과 사업장의 고정 디지털 인프라 보급 정도를 보여줍니다.",
    caution: "한 회선을 여러 명이 쓰므로 개인 이용률과 동일하지 않습니다."
  },
  {
    id: "women-parliament",
    code: "SG.GEN.PARL.ZS",
    category: "society",
    name: "여성 국회의원 비중",
    shortName: "여성 의석",
    unit: "%",
    precision: 1,
    description: "국가 의회의 전체 의석 중 여성이 차지하는 비율입니다.",
    reading: "정치적 대표성과 성별 참여 격차를 살펴보는 국제 비교 지표입니다.",
    caution: "의석 비중만으로 정책 영향력이나 사회 전체의 성평등을 판단할 수는 없습니다."
  }
].map((indicator) => ({
  ...indicator,
  source: "세계은행 World Development Indicators",
  sourceUrl: `https://data.worldbank.org/indicator/${indicator.code}`
}));
